# InterviewAce - local setup and launch
#
# Prompts for your Gemini API key (masked), writes interviewace/.env, and starts the
# server. Run from the interviewace/ directory:
#
#   .\start.ps1

$ErrorActionPreference = 'Stop'

Write-Host ''
Write-Host '========================================' -ForegroundColor Cyan
Write-Host '  InterviewAce - local setup' -ForegroundColor Cyan
Write-Host '========================================' -ForegroundColor Cyan
Write-Host ''

$envPath = Join-Path $PSScriptRoot '.env'

if (Test-Path $envPath) {
    Write-Host ".env already exists at $envPath" -ForegroundColor Yellow
    $answer = Read-Host 'Overwrite it? (y/N)'
    if ($answer -ne 'y') {
        Write-Host 'Keeping the existing .env.' -ForegroundColor Green
        $skipWrite = $true
    }
}

if (-not $skipWrite) {
    # -AsSecureString keeps the key off the screen and out of PSReadLine history.
    $secureKey = Read-Host -Prompt 'Paste your Gemini API key' -AsSecureString
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureKey)
    try {
        $apiKey = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
    }
    finally {
        [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }

    if ([string]::IsNullOrWhiteSpace($apiKey)) {
        Write-Host 'ERROR: no key provided.' -ForegroundColor Red
        exit 1
    }

    # Google issues at least two key shapes: the legacy 39-character "AIza..." form and
    # a newer 53-character dotted form. Only obvious mistakes are rejected here (a
    # pasted URL, an OAuth token, stray whitespace) rather than enforcing a fixed
    # pattern, which would reject valid keys the next time the format changes.
    $looksWrong = $false
    if ($apiKey -match '\s') { $looksWrong = $true; $reason = 'it contains whitespace' }
    elseif ($apiKey.Length -lt 30) { $looksWrong = $true; $reason = 'it is too short' }
    elseif ($apiKey -match '^https?://') { $looksWrong = $true; $reason = 'it looks like a URL' }
    elseif ($apiKey.StartsWith('ya29.')) { $looksWrong = $true; $reason = 'it is an OAuth access token, not an API key' }

    if ($looksWrong) {
        Write-Host "Warning: that does not look like a Gemini API key - $reason." -ForegroundColor Yellow
        $answer = Read-Host 'Continue anyway? (y/N)'
        if ($answer -ne 'y') { exit 1 }
    }

    # Signs session tokens. Generated once so tokens survive server restarts.
    $bytes = New-Object byte[] 36
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $sessionSecret = [Convert]::ToBase64String($bytes)

    $content = @"
# Generated by start.ps1. This file is gitignored - never commit it.
GOOGLE_API_KEY=$apiKey
SESSION_SECRET=$sessionSecret
GOOGLE_GENAI_USE_VERTEXAI=FALSE
PORT=8080
"@

    # Written without a BOM: python-dotenv would otherwise fold the BOM into the first
    # variable name and GOOGLE_API_KEY would silently read as empty.
    [System.IO.File]::WriteAllText($envPath, $content, (New-Object System.Text.UTF8Encoding($false)))

    $apiKey = $null
    Write-Host ''
    Write-Host "Wrote $envPath" -ForegroundColor Green
}

if (Test-Path (Join-Path $PSScriptRoot 'venv\Scripts\Activate.ps1')) {
    Write-Host 'Activating venv...' -ForegroundColor Yellow
    & (Join-Path $PSScriptRoot 'venv\Scripts\Activate.ps1')
}
elseif (Test-Path (Join-Path $PSScriptRoot '.venv\Scripts\Activate.ps1')) {
    Write-Host 'Activating .venv...' -ForegroundColor Yellow
    & (Join-Path $PSScriptRoot '.venv\Scripts\Activate.ps1')
}
else {
    Write-Host 'No venv found. Create one with:' -ForegroundColor Yellow
    Write-Host '  python -m venv venv; .\venv\Scripts\Activate.ps1; pip install -r requirements.txt'
    Write-Host ''
}

# Windows Python installs frequently lack a usable CA bundle for the Live API's TLS
# handshake; certifi's bundle is a reliable fallback.
try {
    $certPath = (python -m certifi) 2>$null
    if ($certPath) { $env:SSL_CERT_FILE = $certPath }
}
catch {
    # certifi not installed; the system trust store will be used.
}

Write-Host ''
Write-Host 'Starting InterviewAce on http://localhost:8080' -ForegroundColor Yellow
Write-Host 'Grant camera and microphone permission when the browser asks.' -ForegroundColor Yellow
Write-Host ''

# Run from interviewace/ using app.main:app. Launching from inside app/ makes `app`
# resolve as a namespace package, which can load modules twice with split session state.
Set-Location $PSScriptRoot
python -m uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
